version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - app-network

  # You can uncomment this section if you want to run your .NET app in Docker too
  # webapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: msapps-server
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=mssql;Database=MsAppsUsers;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
  #   depends_on:
  #     - mssql
  #   networks:
  #     - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge
